import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navigation from "@/components/navigation"
import ThemeSwitcher from "@/components/theme-switcher"
import Providers from "@/components/providers"
import NextTopLoader from "nextjs-toploader"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Plan It! - Put order on your tasks",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang='en'>
        <body className={inter.className}>
          <NextTopLoader color='#fffff' height={10} />
          <div className='flex flex-col min-h-screen dark:bg-dark-blue dark:text-white relative'>
            <div className='flex-1'>
              <Navigation />
              {children}
            </div>
            <ThemeSwitcher />
          </div>
        </body>
      </html>
    </Providers>
  )
}
